### ISSUE TITLE
Something strange in test.js

### ISSUE THREAD

**Issue by cayrodmed1** [netbeast/flower-power-plugin#2]
While trying to make a plugin, I've been having a look at this repository, but I've found something strange in the test.js file.

In this line:
`url: 'http://localhost:8000/i/flower-power-plugin/pablogay/00:1a:7d:da:71:13'`

What does **`pablogay`** mean in this url?

**Comment by jsdario** [comment]
Don't know. Maybe @pablopi or @luisfpinto have the answer...

**Comment by pablopi** [comment]
Luis...
 It was changed to 
`url: 'http://localhost:8000/i/flower-power-plugin/temperature/00:1a:7d:da:71:13`

`/temperature/00:1a:7d:da:71:13` is the hook

`00:1a:7d:da:71:13` identify the device and is used to reach it.
